version: "3"

services:
  postgres:
    image: postgres:10-alpine
    volumes:
      - twain-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-twain}
    restart: unless-stopped
  backend:
    image: twain/backend:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    environment:
      POSTGRES_HOSTNAME: postgres
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  twain-pgdata:
